### ISSUE TITLE
When using the hevc_amf encoder, the mp4/mkv files produced by FFMPEG failed to be time-seeked correctly

### ISSUE THREAD

**Issue by wokmi** [Xaymar/ffmpeg-amf#3]
Hi. awesome coders of AMF please help to fix this problem..
Finally I got one h264/mp4 file converted into a HEVC/mkv file by using FFMPEG command line:
`ffmpeg -i src.mp4 -c:a copy -c:v hevc_amf -vb 1300k -vf scale=940:540 output.mkv`
the converting process seems ok on my old Phemon II X4 B97/RX550 PC with 11x speed.
but then I found out the output mkv can't be time jumped and skip content..the seeking isn't working under MediaPlayerClassic-HD/BE . The mkv file can be played through only from the very beginning .
I've tried the lastest official Win64 build(20171231-2906363) from FFMPEG website and 45e9b36162 build from here FFMPEG-AMF. they both faild to produce seekable mkv/mp4 files(at least by default and I don't know what arguments should I add to make it work. I tried add keyframes,aligning GOP etc).
I inspected the output mp4 files a little. they seem to have the "Format profile" incorrectly marked to  "Main@L6.2@Main" while it should be L3.0 or L3.1. the "auto" option from the "-level" directive seems not working properly.
I can provide sample output file but I think this bug can be reproduced by converting any h264/mp4 file which duration is longer than 10 minutes....

**Comment by wokmi** [comment]
let me know if I can be any helpful to your amf devlopement

**Comment by Xaymar** [comment]
Error is caused by [this file](https://github.com/Xaymar/ffmpeg/blob/amf-ffmpeg-3.4/libavcodec/amfenc.c).

* [Line 326](https://github.com/Xaymar/ffmpeg/blob/amf-ffmpeg-3.4/libavcodec/amfenc.c#L326) incorrectly marks I-Frames as Key-Frames.
* [Line 339](https://github.com/Xaymar/ffmpeg/blob/amf-ffmpeg-3.4/libavcodec/amfenc.c#L339) assigns the "presentation" (it's actually decoding timestamp, as these are out of order) to pts.

Edit: This is for the old integration, newest is on master.

**Comment by Xaymar** [comment]
Please move further discussion to Xaymar/ffmpeg instead.
